"""empty message

Revision ID: 0159e613cc9e
Revises: ab88c4f79211
Create Date: 2022-09-07 17:55:34.898192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0159e613cc9e'
down_revision = 'ab88c4f79211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('images', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('images', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
