"""empty message

Revision ID: 1865937b93fa
Revises: 4bf5227e2181
Create Date: 2022-09-04 19:36:37.922812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1865937b93fa'
down_revision = '4bf5227e2181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('social_media_posts', 'post_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('social_media_posts', 'post_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
