"""empty message

Revision ID: 86c1acc850f4
Revises: 2569e0cdf5a9
Create Date: 2022-09-10 22:52:12.408773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c1acc850f4'
down_revision = '2569e0cdf5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('verified_email', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'contacts', ['email'])
    op.drop_column('contacts', 'valid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('valid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_column('contacts', 'verified_email')
    # ### end Alembic commands ###
