"""empty message

Revision ID: a77b63100d28
Revises: 86c1acc850f4
Create Date: 2022-09-11 11:18:01.183708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77b63100d28'
down_revision = '86c1acc850f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('verification_requested', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'verification_requested')
    # ### end Alembic commands ###
