"""empty message

Revision ID: ab88c4f79211
Revises: 1865937b93fa
Create Date: 2022-09-07 14:07:15.225419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab88c4f79211'
down_revision = '1865937b93fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_hashtags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('hashtag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['social_media_posts.id'], )
    )
    op.add_column('media_uploads', sa.Column('image_id', sa.Integer(), nullable=True))
    op.alter_column('media_uploads', 'clip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'media_uploads', 'images', ['image_id'], ['id'])
    op.add_column('social_media_posts', sa.Column('media_upload_id', sa.Integer(), nullable=True))
    op.alter_column('social_media_posts', 'post_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint('social_media_posts_clip_id_fkey', 'social_media_posts', type_='foreignkey')
    op.create_foreign_key(None, 'social_media_posts', 'media_uploads', ['media_upload_id'], ['id'])
    op.drop_column('social_media_posts', 'clip_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_media_posts', sa.Column('clip_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'social_media_posts', type_='foreignkey')
    op.create_foreign_key('social_media_posts_clip_id_fkey', 'social_media_posts', 'video_clips', ['clip_id'], ['id'])
    op.alter_column('social_media_posts', 'post_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('social_media_posts', 'media_upload_id')
    op.drop_constraint(None, 'media_uploads', type_='foreignkey')
    op.alter_column('media_uploads', 'clip_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('media_uploads', 'image_id')
    op.drop_table('post_hashtags')
    op.drop_table('images')
    op.drop_table('hashtags')
    # ### end Alembic commands ###
